### ISSUE TITLE
Riak search results pagination

### ISSUE THREAD

**Issue by developerworks** [pma/riak_ecto#8]
@pma Hi, there is a issus about search pagination, the pagination can be done within erlang like:

``` erlang
-define(ROWS_PER_PAGE, 2).

Page = 2,
Start = ?ROWS_PER_PAGE * (Page - 1),

riakc_pb_socket:search(Pid, <<"famous">>, <<"*:*">>, [{start, Start},{rows, ?ROWS_PER_PAGE}]),
```

But, how to do it in the `riak_ecto` lib ? 
How can i pass the `"*:*"` to `riakc_pb_socket:search` through `riak_ecto`?

**Comment by pma** [comment]
Use Ecto.Query limit and offset options: https://hexdocs.pm/ecto/Ecto.Query.html#limit/3

The Riak Ecto adapter supports both.

You should avoid doing deep pagination. If you allow the client to requests page nr. 50_000, while displaying 100 records per page, the Solr node will most likely crash with an OutOfMemoryException. Enforce a max page number and allow results to be filtered.
