### ISSUE TITLE
About sort of search results

### ISSUE THREAD

**Issue by developerworks** [pma/riak_ecto#9]
Seems like the results of search query have no sort, i must use mapred to sort the results of query ?

**Comment by pma** [comment]
@developerworks Refer to Ecto.Query.order_by/3 (https://hexdocs.pm/ecto/Ecto.Query.html#order_by/3). It is supported by the Riak adapter.

Note: The Solr schema must specify the field to sort by as `indexed="true"`.

**Comment by developerworks** [comment]
Thanks.
